### ISSUE TITLE
bad levensthein distance

### ISSUE THREAD

**Issue by videokojot** [rangp/fuzzystrings#2]
Levensthein distance for "renomia" and "remonia" is 2, but library computes 3.

**Comment by kimpenhaus** [comment]
not sure if you are using the latest bits?

quick test shows up with calculated distance of _**2**_:

![bildschirmfoto 2017-03-13 um 13 20 18](https://cloud.githubusercontent.com/assets/575109/23854067/ef067686-07ef-11e7-93be-ea9d846ffa87.png)

**Comment by rangp** [comment]
Please note that this is not the original FuzzyStrings repository but a fork I made. I forgot to mention that we encountered the same bug as you and fixed it in this fork. Just updated the readme.md to account for those changes. 

You can download this fork under https://www.nuget.org/packages/FuzzyStrings.NetStandard/
The original repository can be found under https://www.nuget.org/packages/DuoVia.FuzzyStrings/

**Comment by videokojot** [comment]
I am sorry - my mistake - you are right - it works now. Thank you very much for your fork.
